- name: CREATE VM
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'vnet', 'subnet', 'vmname' and 'resgrp' need to be provided at command line with arg --extra-vars
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      account_type: Standard_LRS
  - name: Create security group that allows SSH and HTTP
    azure_rm_securitygroup: 
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      rules: 
        - name: SSH 
          protocol: Tcp 
          destination_port_range: 22  
          access: Allow  
          priority: 101 
          direction: Inbound
        - name: WEB
          protocol: Tcp 
          destination_port_range: 80  
          access: Allow  
          priority: 102 
          direction: Inbound
  - name: Create public IP address
    azure_rm_publicipaddress: 
      resource_group: '{{ resgrp }}'
      allocation_method: Static 
      name: '{{ vmname }}'
      domain_name_label: '{{ vmname }}'
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      virtual_network: '{{ vnet }}'
      subnet: '{{ subnet }}'
      public_ip_name: '{{ vmname }}'
      security_group: '{{ vmname }}'
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      storage_account: '{{ vmname }}'
      storage_container: '{{ vmname }}'
      storage_blob: '{{ vmname }}.vhd'
      network_interfaces: '{{ vmname }}'
      vm_size: Standard_A0
      admin_username: lab-user
      ssh_password_enabled: False
      ssh_public_keys: 
        - path: /home/nitinpokharna/.ssh/authorized_keys
          key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcfHG3DR6WZEdzFekria6wROlBP5kq1+4JliLRKVskcTTQWJr0vCoh5Q2qHlOWoQqqI+eonMoq3n9ISoJ5vsDtO7XH+HCmbTA7vcD7zcOSQIc9uc+swn8hvwdIUtaSSEem68sgwpx4DiotebUpR/noja/sQh+nSHYt5NPARsu1y+zPxLnLpe6q/cJOHxZULV8zD/JSODBMko1MzOSk7lX3CxLs0uXuMjro4x35/OFnxpzOO51Cv0BjKvx1IdhZqMmoyuFUWXgmzMD7IAGETL9SQFfpoW8ai8Rn+C0rlVLTru0FTR8bMqk7zPk9bNdFXlv33lWmtDL/Cx0W2LuiY0k/ nitinpokharna@AnsibleVM'
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.2'
        version: latest